FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /

COPY calendar-api/ ./
COPY global_modules/ ./global_modules/
COPY middlewares/ ./middlewares/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]