services:

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow
    command: ["postgres"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - smm_network
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5432 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 256M

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    depends_on:
      postgres:
        condition: service_healthy
    command: ["python", "main.py"]
    restart: unless-stopped
    volumes:
      - ./logs:/logs:rw
      - ./json:/app/json:rw
      - ./storage_data:/storage_data:rw
      - ./sessions:/sessions:rw
    networks:
      - smm_network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M

volumes:
  postgres_data:
    driver: local
    name: smm_manager_postgres_data

networks:
  smm_network:
