FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY executors/ ./
COPY global_modules/ ./global_modules/
COPY json/ ./json/

CMD ["python", "main.py"]