FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /

COPY executors/ ./
COPY global_modules/ ./global_modules/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]